module.exports = {
  extends: ['@commitlint/cli', '@commitlint/config-conventional'],
  rules: {
    'type-enum': [
      2,
      'always',
      [
        'feat',
        'fix',
        'refactor',
        'docs',
        'style',
        'refactor:deps',
        'test',
        'chore',
        'revert',
        'merge',
        'workflow',
        'ci',
        'release',
        'bump',
        'build',
        'perf',
        'revert:merge',
        'revert:chore',
        'revert:feat',
        'revert:fix',
        'revert:refactor',
        'revert:refactor:deps',
        'revert:docs',
        'revert:style',
        'revert:test',
        'revert:chore/workflow',
        'revert:chore/ci',
        'revert:chore/release',
        'revert:chore/bump',
        'revert:chore/build',
        'revert:chore/perf',
        'revert:chore/revert:merge',
      ],
    ],
    'subject-case': [2, 'always', 'sentence-case'],
  },
};
